# Generated by manual definition for initial schema
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("management", "Management"), ("operationnel", "Opérationnel"), ("support", "Support")], max_length=32)),
                ("description", models.TextField(blank=True)),
                ("completeness", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="processes", to="smq.department")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_processes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("name", "department")}},
        ),
        migrations.CreateModel(
            name="ProcessDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="process_documents/")),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("status", models.CharField(default="brouillon", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("process", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="smq.process")),
            ],
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("interne", "Interne"), ("externe", "Externe")], max_length=16)),
                ("status", models.CharField(choices=[("planifie", "Planifié"), ("en_cours", "En cours"), ("clos", "Clos")], default="planifie", max_length=16)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("report", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_audits", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="audits", to="smq.department")),
            ],
        ),
        migrations.CreateModel(
            name="NonConformity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("severity", models.CharField(choices=[("critique", "Critique"), ("majeure", "Majeure"), ("mineure", "Mineure")], max_length=16)),
                ("status", models.CharField(choices=[("ouverte", "Ouverte"), ("en_cours", "En cours"), ("resolue", "Résolue")], default="ouverte", max_length=16)),
                ("description", models.TextField()),
                ("detected_at", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("audit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="non_conformities", to="smq.audit")),
                ("process", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="non_conformities", to="smq.process")),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("status", models.CharField(choices=[("brouillon", "Brouillon"), ("revision", "En révision"), ("approuve", "Approuvé")], default="brouillon", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to=settings.AUTH_USER_MODEL)),
                ("related_process", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="related_documents", to="smq.process")),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("evidence", models.FileField(blank=True, null=True, upload_to="actions_evidence/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_actions", to=settings.AUTH_USER_MODEL)),
                ("non_conformity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="smq.nonconformity")),
            ],
        ),
        migrations.CreateModel(
            name="Kpi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_process", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kpis", to="smq.process")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("admin", "Administrateur / Responsable Qualité"), ("gestionnaire", "Gestionnaire de processus"), ("auditeur_interne", "Auditeur interne"), ("auditeur_externe", "Auditeur externe")], max_length=32)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="members", to="smq.department")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="audit",
            name="processes",
            field=models.ManyToManyField(related_name="audits", to="smq.process"),
        ),
        migrations.AddField(
            model_name="audit",
            name="team",
            field=models.ManyToManyField(related_name="audit_missions", to=settings.AUTH_USER_MODEL),
        ),
    ]
