# Generated by Django 5.0.14 on 2026-04-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smq', '0002_isoclause_processsheettemplate_auditassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
