# Generated by Django 5.0.14 on 2026-04-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smq', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditComputedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conformity_level', models.CharField(blank=True, max_length=64)),
                ('conformity_label', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computed_result', to='smq.auditassignment')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScaleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('truth_label', models.CharField(max_length=255)),
                ('truth_choice', models.CharField(max_length=64)),
                ('truth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conformity_level', models.CharField(max_length=64)),
                ('conformity_label', models.TextField()),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='smq.evaluationscale')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
