# Generated by Django 5.0.14 on 2026-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smq', '0011_blank_legacy_draft_process_sheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable_qualite', 'Responsable qualité'), ('gestionnaire', 'Gestionnaire de processus'), ('auditeur_interne', 'Auditeur interne'), ('auditeur_externe', 'Auditeur externe')], max_length=32),
        ),
    ]
