# Generated by Django 5.0.14 on 2026-05-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smq', '0013_isocriterion_weight_correctiveactionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Créé'), ('updated', 'Mis à jour'), ('sheet_updated', 'Fiche mise à jour'), ('bpmn_updated', 'BPMN mis à jour'), ('status_changed', 'Statut modifié')], default='updated', max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_history', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='smq.process')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
